// <auto-generated />
namespace TicariOtomasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class kargoDeneme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(kargoDeneme));
        
        string IMigrationMetadata.Id
        {
            get { return "202202100618221_kargoDeneme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
